name=input("Enter any name:")
print("Upper :",name.upper())
print("Lower :",name.lower())
print("Proper :",name.capitalize())
'''print("Casefold :",name.casefold())'''
print("isupper :",name.isupper())
print("islower:",name.islower())
print("isdigit",name.isdigit())
print("isnumber",name.isnumeric())
print("isalpha",name.isalpha())
print("isalnum",name.isalnum())
print("isspace",name.isspace())
print(name.center(50,"*"))
print(name.count("a",3,10))
print(name.find("tan"))
print(name.index("a"))
print(name.startswith("t"))
print(name.endswith("t"))
print(name.removeprefix("t"))
print(name.removesuffix("t"))
print(name.replace("t","r"))
print(name.replace("t","r",1))