name=("Navjot","taranvir","Manpreet")
number=(1,5,7,2,34,5,6,78,9,90)
print(name)
print(sum(number))
print(max(number))
print(min(number))
for i in name:
    print(i.upper())
print(number.count(5))
print(number.index(78))
